# This is a sample build configuration for C++ – Make.
# -----

clone:
  lfs: true    # enable git lfs to use GCC 8.4 deb package

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build for CPU and run Python tests
          image: tensorflow/tensorflow:2.3.0
          caches:
            - build-folder    # cache build folder with the compiled binaries
          script:
            - apt update && apt install -y wget git apt-transport-https ca-certificates gnupg software-properties-common
            - wget --tries=10 --retry-connrefused -q -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
            - apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
            - apt update && apt install -y cmake=3.18.3-0kitware1 cmake-data=3.18.3-0kitware1
            - git submodule update --init --recursive
            - dpkg -i core/toolchain/gcc-8.4_8.4-1_x86_64.deb
            - find core/thirdparty -type f -exec touch -t 202009040101 {} +
            - mkdir -p build && cd build
            - CC=/usr/local/bin/gcc8.4 CXX=/usr/local/bin/g++8.4 cmake -DWITH_CUDNN=OFF ..
            - make -j4
            - cd ..
            - cp build/libs/_upstride.so src/python/upstride/type_generic
            - cp build/core/thirdparty/onednn/src/libdnnl.so.1 src/python/upstride/type_generic
            - python test.py
            - echo "All good."

definitions:
  caches:
    build-folder: build
